### ISSUE TITLE
PRs not merged, instead error reported in comment "Error: Not Found"

### ISSUE THREAD

**Issue by cdaringe** [greenkeeper-keeper/hapi-greenkeeper-keeper#140]
# problem statement

- PRs are not being merged when configured well & all systems up

# discussion

## proof of configuration

let us examine [this case](https://github.com/cdaringe/3d-adjacency/pull/17#issuecomment-301679209)

- clearly, all ENV secrets are loaded full well to establish this two way communication
- only the new greenkeeper integration is loaded (that is, the old deprecated greenkeeper service is not applied)
- the same error occurs both with `pull_request` and with `status`, only one at a time

<img width="500" alt="screen shot 2017-05-15 at 10 46 36 pm" src="https://cloud.githubusercontent.com/assets/1003261/26091501/8281ca12-39c0-11e7-82ee-373c411c2867.png">
<img width="511" alt="screen shot 2017-05-15 at 10 46 49 pm" src="https://cloud.githubusercontent.com/assets/1003261/26091500/827a1538-39c0-11e7-887c-03009efccfd8.png">

**Comment by travi** [comment]
hmm, i guess i looked at your issue a bit wrong yesterday. i didn't realize that you had to manually merge it. i thought your bot merged it, but you also got the error comment. 

i dont think i've seen very many cases where it simply doesn't get merged when things are passing and webhooks are being sent correctly (i have noticed that some success events never fire for travis builds).

i assume that the webhooks are sending correctly since you are getting the failure as the comment (you can confirm in the list below the screenshot you took, if there is doubt). any chance that there is any additional info in the server logs?

**Comment by travi** [comment]
did we end up solving this problem?

**Comment by cdaringe** [comment]
i had turned off my gkk instance. i recently revived gk on a ton of projects--ill be firing it back up again soon!  let's close it until i can reproduce. sorry for keepin it open for so long!

**Comment by travi** [comment]
no worries. i havent had time to give much attention to this project after we had an addition to our family, so i was hoping i at least hadnt dropped the ball on an issue that was still causing you trouble. thanks for the quick response

**Comment by cdaringe** [comment]
congrats! 👶

**Comment by travi** [comment]
thanks :)

once you get things up and going again, dont let me slack too bad if you do run into any trouble
